services:
  - type: web
    name: tsa-wait-proxy
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    region: ohio
